### ISSUE TITLE
Pretty print XML

### ISSUE THREAD

**Issue by kulnor** [mtna/imagemagick-identify-parser#2]
Enhance XML serializer to pretty print the output

**Comment by wsdookadr** [comment]
Implemented in c9c81ddb0e

**Comment by kulnor** [comment]
The minidom parser fails when parsing the XML from the sample.dcm file. It complains about invalid content at column 46078 which corresponds to the following element:
`<ReferencedImageSequence>þÿ</ReferencedImageSequence>`
Similar elements follow.

When looking at the original text output from identify, this looks like
`dcm:ReferencedImageSequence: ??`
but opening the .txt file does seem to show unusual characters
`dcm:ReferencedImageSequence: ˛ˇ`
Not sure what the correct value is.
In the JSON version, this gets serialized as 
`"ReferencedImageSequence": "\u00fe\u00ff"`
This may then need to be properly escaped in the XML which should be someting like
&#x00fe;&#x00ff;
At the same time no sure if these values make any sense or have any usefulness. But should fix anyway.

**Comment by kulnor** [comment]
Note that at the same time, "þÿ" is not particularly invalid in XML. May just be that minidom does not like these values.
